#![cfg_attr(rustfmt, rustfmt_skip)]
//! Tables and function for `ISO_IR_6`

use crate::tables::{BackwardResult, ForwardResult};
// cSpell:disable

// Do not edit! This file was autogenerated with `gen_single_byte_tables.py`
// utility on 2023-02-06 by "stingx" on "DESKTOP-2IQN19A".

/// Conversion single-byte -> unicode for `ISO_IR_6`
pub fn forward_g0_iso_ir_6(input: &[u8]) -> ForwardResult {
    let c = input[0];
    match c {
        // CL, GL
        ..=0x7F => (1, Some(c as u32)),
        // CR, GR
        _ => (1, None)
    }
}

/// Conversion unicode -> single-byte for `ISO_IR_6`
pub fn backward_g0_iso_ir_6(output: &mut [u8], code: u32) -> BackwardResult {
    match code {
        // CL, GL
        ..=0x7F => {
            output[0] = code as u8;
            Some(1)
        },
        // CR, GR, Invalid
        _ => None
    }
}
