// This file contains constant definition for [Meta] information
// for the DICOM constant tags.
//
// Do not edit! This file was autogenerated with `mk_tags_rs`
// utility on Thu, 19 Jan 2023 02:14:43 +0300 by "stingx" on "desktop-2iqn19a".
//
// Full command line:
// target\debug\mk_tags_rs.exe -i libs/dpx-dicom-core/etc/diconde.tsv -t libs/dpx-dicom-core/src/tag/diconde.rs -m libs/dpx-dicom-core/src/tag/diconde_meta.rs
//
#![allow(non_upper_case_globals, unused_imports)]
use crate::{Tag, TagKey};
use std::borrow::Cow;

/// (0010,0010) PN 1 Component Name
pub const ComponentName : Tag = Tag{ key: TagKey(0x00100010), creator: None};
/// (0010,0020) LO 1-n Component ID Number
pub const ComponentIDNumber : Tag = Tag{ key: TagKey(0x00100020), creator: None};
/// (0010,1000) LO 1-n Other Component IDs
pub const OtherComponentIDs : Tag = Tag{ key: TagKey(0x00101000), creator: None};
/// (0010,1001) PN 1-n Other Component Names
pub const OtherComponentNames : Tag = Tag{ key: TagKey(0x00101001), creator: None};
/// (0010,0030) DA 1 Component Manufacturing Date
pub const ComponentManufacturingDate : Tag = Tag{ key: TagKey(0x00100030), creator: None};
/// (0010,4000) LT 1 Component Notes
pub const ComponentNotes : Tag = Tag{ key: TagKey(0x00104000), creator: None};
/// (0010,2160) SH 1 Material Name
pub const MaterialName : Tag = Tag{ key: TagKey(0x00102160), creator: None};
/// (0008,0090) PN 1 Component Owner Name
pub const ComponentOwnerName : Tag = Tag{ key: TagKey(0x00080090), creator: None};
/// (0008,1048) PN 1-n Inspecting Company Name
pub const InspectingCompanyName : Tag = Tag{ key: TagKey(0x00081048), creator: None};
/// (0008,1060) PN 1-n Certifying Inspector Name
pub const CertifyingInspectorName : Tag = Tag{ key: TagKey(0x00081060), creator: None};
/// (0032,4000) LT 1 Examination Notes
pub const ExaminationNotes : Tag = Tag{ key: TagKey(0x00324000), creator: None};
/// (0008,1050) PN 1-n Inspector Name
pub const InspectorName : Tag = Tag{ key: TagKey(0x00081050), creator: None};
/// (0008,0080) LO 1 Company Name
pub const CompanyName : Tag = Tag{ key: TagKey(0x00080080), creator: None};
/// (0008,0081) ST 1 Company Address
pub const CompanyAddress : Tag = Tag{ key: TagKey(0x00080081), creator: None};
/// (0008,1040) LO 1 Department Name
pub const DepartmentName : Tag = Tag{ key: TagKey(0x00081040), creator: None};
/// (0018,1008) LO 1 Scanner ID
pub const ScannerID : Tag = Tag{ key: TagKey(0x00181008), creator: None};
/// (0040,A30A) DS 1-n Property Value
pub const PropertyValue : Tag = Tag{ key: TagKey(0x0040A30A), creator: None};
/// (0040,08EA) SQ 1 Property Units Code Sequence
pub const PropertyUnitsCodeSequence : Tag = Tag{ key: TagKey(0x004008EA), creator: None};
/// (0070,0023) CS 1 Indication ROI Geometric Type
pub const IndicationROIGeometricType : Tag = Tag{ key: TagKey(0x00700023), creator: None};
/// (0040,A040) CS 1 Indication ROI Value Type
pub const IndicationROIValueType : Tag = Tag{ key: TagKey(0x0040A040), creator: None};
/// (0070,0021) US 1 Number of ROI Contour Points
pub const NumberOfROIContourPoints : Tag = Tag{ key: TagKey(0x00700021), creator: None};
/// (0070,0022) DS 2-n Indication ROI Contour Data
pub const IndicationROIContourData : Tag = Tag{ key: TagKey(0x00700022), creator: None};
/// (0008,2124) IS 1 Number of Surfaces
pub const NumberOfSurfaces : Tag = Tag{ key: TagKey(0x00082124), creator: None};
/// (0008,212A) IS 1 Number of Total Channels
pub const NumberOfTotalChannels : Tag = Tag{ key: TagKey(0x0008212A), creator: None};
/// (0008,2122) IS 1 Surface Number
pub const SurfaceNumber : Tag = Tag{ key: TagKey(0x00082122), creator: None};
/// (0008,2127) SH 1 Channel Name
pub const ChannelName : Tag = Tag{ key: TagKey(0x00082127), creator: None};
/// (0008,2128) IS 1 Channel Number
pub const ChannelNumber : Tag = Tag{ key: TagKey(0x00082128), creator: None};
/// (0018,6014) US 1 Pixel Data Type
pub const PixelDataType : Tag = Tag{ key: TagKey(0x00186014), creator: None};
/// (0009,1020,"astm.org/diconde/iod/ComponentStudy") DA 1 Expiry Date RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const ExpiryDate_CompStudy : Tag = Tag{ key: TagKey(0x00091020), creator: Some(Cow::Borrowed("astm.org/diconde/iod/ComponentStudy"))};
/// (0009,1010,"astm.org/diconde/iod/ComponentSeries") ST 1 Actual Environmental Conditions RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const ActualEnvironmentalConditions_CompSeries : Tag = Tag{ key: TagKey(0x00091010), creator: Some(Cow::Borrowed("astm.org/diconde/iod/ComponentSeries"))};
/// (0009,1040,"astm.org/diconde/iod/ComponentSeries") ST 1 Environmental Conditions RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const EnvironmentalConditions_CompSeries : Tag = Tag{ key: TagKey(0x00091040), creator: Some(Cow::Borrowed("astm.org/diconde/iod/ComponentSeries"))};
/// (0011,1023,"astm.org/diconde/iod/Component") ST 1-n CAD File Format RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const CADFileFormat_Component : Tag = Tag{ key: TagKey(0x00111023), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1024,"astm.org/diconde/iod/Component") ST 1-n Component Ref System RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const ComponentRefSystem_Component : Tag = Tag{ key: TagKey(0x00111024), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1025,"astm.org/diconde/iod/Component") ST 1-n Component Manufacturing Procedure RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const ComponentManufacturingProcedure_Component : Tag = Tag{ key: TagKey(0x00111025), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1028,"astm.org/diconde/iod/Component") ST 1-n Component Manufacturer RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const ComponentManufacturer_Component : Tag = Tag{ key: TagKey(0x00111028), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1030,"astm.org/diconde/iod/Component") DS 1-n Thickness RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const Thickness_Component : Tag = Tag{ key: TagKey(0x00111030), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1032,"astm.org/diconde/iod/Component") DS 1-n Material Pipe Diameter RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialPipeDiameter_Component : Tag = Tag{ key: TagKey(0x00111032), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1034,"astm.org/diconde/iod/Component") DS 1-n Material Isolation Diameter RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialIsolationDiameter_Component : Tag = Tag{ key: TagKey(0x00111034), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1042,"astm.org/diconde/iod/Component") ST 1-n Material Grade RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialGrade_Component : Tag = Tag{ key: TagKey(0x00111042), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1044,"astm.org/diconde/iod/Component") ST 1-n Material Properties File ID RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialPropertiesFileID_Component : Tag = Tag{ key: TagKey(0x00111044), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1045,"astm.org/diconde/iod/Component") ST 1-n Material Properties File Format RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialPropertiesFileFormat_Component : Tag = Tag{ key: TagKey(0x00111045), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1046,"astm.org/diconde/iod/Component") LT 1 Material Notes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MaterialNotes_Component : Tag = Tag{ key: TagKey(0x00111046), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1050,"astm.org/diconde/iod/Component") CS 1 Shape RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const Shape_Component : Tag = Tag{ key: TagKey(0x00111050), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1052,"astm.org/diconde/iod/Component") CS 1 Curvature Type RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const CurvatureType_Component : Tag = Tag{ key: TagKey(0x00111052), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1054,"astm.org/diconde/iod/Component") DS 1 Outer Diameter RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const OuterDiameter_Component : Tag = Tag{ key: TagKey(0x00111054), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0011,1056,"astm.org/diconde/iod/Component") DS 1 Inner Diameter RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const InnerDiameter_Component : Tag = Tag{ key: TagKey(0x00111056), creator: Some(Cow::Borrowed("astm.org/diconde/iod/Component"))};
/// (0021,1002,"astm.org/diconde/iod/NdeIndication") SQ 1 Evaluator Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const EvaluatorSequence_Indication : Tag = Tag{ key: TagKey(0x00211002), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1004,"astm.org/diconde/iod/NdeIndication") IS 1 Evaluator Number RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const EvaluatorNumber_Indication : Tag = Tag{ key: TagKey(0x00211004), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1006,"astm.org/diconde/iod/NdeIndication") PN 1 Evaluator Name RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const EvaluatorName_Indication : Tag = Tag{ key: TagKey(0x00211006), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1008,"astm.org/diconde/iod/NdeIndication") IS 1 Evaluation Attempt RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const EvaluationAttempt_Indication : Tag = Tag{ key: TagKey(0x00211008), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1012,"astm.org/diconde/iod/NdeIndication") SQ 1 Indication Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationSequence_Indication : Tag = Tag{ key: TagKey(0x00211012), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1014,"astm.org/diconde/iod/NdeIndication") IS 1 Indication Number RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationNumber_Indication : Tag = Tag{ key: TagKey(0x00211014), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1016,"astm.org/diconde/iod/NdeIndication") SH 1 Indication Label RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationLabel_Indication : Tag = Tag{ key: TagKey(0x00211016), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1018,"astm.org/diconde/iod/NdeIndication") ST 1 Indication Description RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationDescription_Indication : Tag = Tag{ key: TagKey(0x00211018), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,101A,"astm.org/diconde/iod/NdeIndication") CS 1-n Indication Type RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationType_Indication : Tag = Tag{ key: TagKey(0x0021101A), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,101C,"astm.org/diconde/iod/NdeIndication") CS 1 Indication Disposition RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationDisposition_Indication : Tag = Tag{ key: TagKey(0x0021101C), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,101E,"astm.org/diconde/iod/NdeIndication") SQ 1 Indication ROI Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationROISequence_Indication : Tag = Tag{ key: TagKey(0x0021101E), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1020,"astm.org/diconde/iod/NdeIndication") CS 1 Indication ROI Geometric Type RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationROIGeometricType_Indication : Tag = Tag{ key: TagKey(0x00211020), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1022,"astm.org/diconde/iod/NdeIndication") IS 1 Number of ROI Contour Points RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfROIContourPoints_Indication : Tag = Tag{ key: TagKey(0x00211022), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1024,"astm.org/diconde/iod/NdeIndication") DS 3-3n Indication ROI Contour Data RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationROIContourData_Indication : Tag = Tag{ key: TagKey(0x00211024), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1026,"astm.org/diconde/iod/NdeIndication") CS 3-3 Indication ROI Contour PointUnits RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationROIContourPointUnits_Indication : Tag = Tag{ key: TagKey(0x00211026), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1028,"astm.org/diconde/iod/NdeIndication") IS 1 Indication ROI Dimensionality RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationROIDimensionality_Indication : Tag = Tag{ key: TagKey(0x00211028), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1030,"astm.org/diconde/iod/NdeIndication") SQ 1 Indication Physical Property Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const IndicationPhysicalPropertySequence_Indication : Tag = Tag{ key: TagKey(0x00211030), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1032,"astm.org/diconde/iod/NdeIndication") SH 1 Property Label RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const PropertyLabel_Indication : Tag = Tag{ key: TagKey(0x00211032), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1034,"astm.org/diconde/iod/NdeIndication") DS 1 Property Value RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const PropertyValue_Indication : Tag = Tag{ key: TagKey(0x00211034), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1036,"astm.org/diconde/iod/NdeIndication") CS 1 Property Units RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const PropertyUnits_Indication : Tag = Tag{ key: TagKey(0x00211036), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeIndication"))};
/// (0021,1002,"astm.org/diconde/iod/NDEGeometry") IS 1 Number of Axes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfAxes_Geometry2 : Tag = Tag{ key: TagKey(0x00211002), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1004,"astm.org/diconde/iod/NDEGeometry") SQ 1 Axes Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxesSequence_Geometry : Tag = Tag{ key: TagKey(0x00211004), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1006,"astm.org/diconde/iod/NDEGeometry") ST 1 Axis Description RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxisDescription_Geometry : Tag = Tag{ key: TagKey(0x00211006), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1008,"astm.org/diconde/iod/NDEGeometry") CS 1 DataSet Mapping RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DataSetMapping_Geometry : Tag = Tag{ key: TagKey(0x00211008), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,100A,"astm.org/diconde/iod/NDEGeometry") IS 1 Axis Number RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxisNumber_Geometry : Tag = Tag{ key: TagKey(0x0021100A), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,100C,"astm.org/diconde/iod/NDEGeometry") CS 1 Axis Type RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxisType_Geometry : Tag = Tag{ key: TagKey(0x0021100C), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,100E,"astm.org/diconde/iod/NDEGeometry") CS 1 Axis Units RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxisUnits_Geometry : Tag = Tag{ key: TagKey(0x0021100E), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1010,"astm.org/diconde/iod/NDEGeometry") OB 1 Axis Values RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AxisValues_Geometry : Tag = Tag{ key: TagKey(0x00211010), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1020,"astm.org/diconde/iod/NDEGeometry") SQ 1 Transform Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TransformSequence_Geometry : Tag = Tag{ key: TagKey(0x00211020), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1022,"astm.org/diconde/iod/NDEGeometry") ST 1 Transform Description RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TransformDescription_Geometry : Tag = Tag{ key: TagKey(0x00211022), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1024,"astm.org/diconde/iod/NDEGeometry") IS 1 Number of Axes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfAxes_Geometry24 : Tag = Tag{ key: TagKey(0x00211024), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1026,"astm.org/diconde/iod/NDEGeometry") IS 1-n Order of Axes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const OrderOfAxes_Geometry : Tag = Tag{ key: TagKey(0x00211026), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,1028,"astm.org/diconde/iod/NDEGeometry") CS 1 Transformed Axis Units RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TransformedAxisUnits_Geometry : Tag = Tag{ key: TagKey(0x00211028), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,102A,"astm.org/diconde/iod/NDEGeometry") DS 1-n Rotation and Scale Matrix RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const RotationAndScaleMatrix_Geometry : Tag = Tag{ key: TagKey(0x0021102A), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0021,102C,"astm.org/diconde/iod/NDEGeometry") DS 11-11 Translation Matrix RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TranslationMatrix_Geometry : Tag = Tag{ key: TagKey(0x0021102C), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NDEGeometry"))};
/// (0009,1002,"astm.org/diconde/iod/NdeCTImage") IS 1 LINAC Energy RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const LINACEnergy_CtImage : Tag = Tag{ key: TagKey(0x00091002), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCTImage"))};
/// (0009,1004,"astm.org/diconde/iod/NdeCTImage") IS 1 LINAC Output RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const LINACOutput_CtImage : Tag = Tag{ key: TagKey(0x00091004), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCTImage"))};
/// (0009,1011,"astm.org/diconde/iod/NdeCtDetector") DS 1 Internal Detector Frame Time RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const InternalDetectorFrameTime_CtDetector : Tag = Tag{ key: TagKey(0x00091011), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1012,"astm.org/diconde/iod/NdeCtDetector") DS 1 Number Of Frames Integrated RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfFramesIntegrated_CtDetector : Tag = Tag{ key: TagKey(0x00091012), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1020,"astm.org/diconde/iod/NdeCtDetector") SQ 1 Detector Temperature Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DetectorTemperatureSequence_CtDetector : Tag = Tag{ key: TagKey(0x00091020), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1022,"astm.org/diconde/iod/NdeCtDetector") DS 1 Sensor Name RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const SensorName_CtDetector : Tag = Tag{ key: TagKey(0x00091022), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1024,"astm.org/diconde/iod/NdeCtDetector") DS 1 Horizontal Offset RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const HorizontalOffset_CtDetector : Tag = Tag{ key: TagKey(0x00091024), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1026,"astm.org/diconde/iod/NdeCtDetector") DS 1 Vertical Offset RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const VerticalOffset_CtDetector : Tag = Tag{ key: TagKey(0x00091026), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1028,"astm.org/diconde/iod/NdeCtDetector") DS 1 Temperature RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const Temperature_CtDetector : Tag = Tag{ key: TagKey(0x00091028), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtDetector"))};
/// (0009,1040,"astm.org/diconde/iod/NdeCtCalibrationData") SQ 1 Dark Current Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DarkCurrentSequence_CtCalData : Tag = Tag{ key: TagKey(0x00091040), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1050,"astm.org/diconde/iod/NdeCtCalibrationData") OB or OW 1 Dark Current Counts RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DarkCurrentCounts_CtCalData : Tag = Tag{ key: TagKey(0x00091050), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1060,"astm.org/diconde/iod/NdeCtCalibrationData") SQ 1 Gain Correction Reference Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const GainCorrectionReferenceSequence_CtCalData : Tag = Tag{ key: TagKey(0x00091060), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1070,"astm.org/diconde/iod/NdeCtCalibrationData") OB or OW 1 Air Counts RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AirCounts_CtCalData : Tag = Tag{ key: TagKey(0x00091070), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1071,"astm.org/diconde/iod/NdeCtCalibrationData") DS 1 KV Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const KVUsedInGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091071), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1072,"astm.org/diconde/iod/NdeCtCalibrationData") DS 1 MAs Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MAsUsedInGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091072), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1073,"astm.org/diconde/iod/NdeCtCalibrationData") DS 1 Number of Frames RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfFrames_CtCalData : Tag = Tag{ key: TagKey(0x00091073), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1074,"astm.org/diconde/iod/NdeCtCalibrationData") LO 1 Filter Material Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const FilterMaterialUsedInGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091074), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1075,"astm.org/diconde/iod/NdeCtCalibrationData") DS 1 Filter Thickness Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const FilterThicknessUsedInGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091075), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1076,"astm.org/diconde/iod/NdeCtCalibrationData") DA 1-n Date of Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DateOfGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091076), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1077,"astm.org/diconde/iod/NdeCtCalibrationData") TM 1-n Time of Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TimeOfGainCalibration_CtCalData : Tag = Tag{ key: TagKey(0x00091077), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1080,"astm.org/diconde/iod/NdeCtCalibrationData") OB 1 Bad Pixel Image RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const BadPixelImage_CtCalData : Tag = Tag{ key: TagKey(0x00091080), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1099,"astm.org/diconde/iod/NdeCtCalibrationData") LT 1 Calibration Notes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const CalibrationNotes_CtCalData : Tag = Tag{ key: TagKey(0x00091099), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeCtCalibrationData"))};
/// (0009,1011,"astm.org/diconde/iod/NdeDxDetector") DS 1 Internal Detector Frame Time RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const InternalDetectorFrameTime_DxDetector : Tag = Tag{ key: TagKey(0x00091011), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1012,"astm.org/diconde/iod/NdeDxDetector") DS 1 Number of Frames Integrated RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfFramesIntegrated_DxDetector : Tag = Tag{ key: TagKey(0x00091012), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1020,"astm.org/diconde/iod/NdeDxDetector") SQ 1 Detector Temperature Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DetectorTemperatureSequence_DxDetector : Tag = Tag{ key: TagKey(0x00091020), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1022,"astm.org/diconde/iod/NdeDxDetector") DS 1 Sensor Name RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const SensorName_DxDetector : Tag = Tag{ key: TagKey(0x00091022), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1024,"astm.org/diconde/iod/NdeDxDetector") DS 1 Horizontal Offset RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const HorizontalOffset_DxDetector : Tag = Tag{ key: TagKey(0x00091024), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1026,"astm.org/diconde/iod/NdeDxDetector") DS 1 Vertical Offset RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const VerticalOffset_DxDetector : Tag = Tag{ key: TagKey(0x00091026), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1028,"astm.org/diconde/iod/NdeDxDetector") DS 1 Temperature RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const Temperature_DxDetector : Tag = Tag{ key: TagKey(0x00091028), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxDetector"))};
/// (0009,1040,"astm.org/diconde/iod/NdeDxCalibrationData") SQ 1 Dark Current Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DarkCurrentSequence_DxCalData : Tag = Tag{ key: TagKey(0x00091040), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1050,"astm.org/diconde/iod/NdeDxCalibrationData") OB or OW 1 Dark Current Counts RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DarkCurrentCounts_DxCalData : Tag = Tag{ key: TagKey(0x00091050), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1060,"astm.org/diconde/iod/NdeDxCalibrationData") SQ 1 Gain Correction Reference Sequence RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const GainCorrectionReferenceSequence_DxCalData : Tag = Tag{ key: TagKey(0x00091060), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1070,"astm.org/diconde/iod/NdeDxCalibrationData") OB or OW 1 Air Counts RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const AirCounts_DxCalData : Tag = Tag{ key: TagKey(0x00091070), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1071,"astm.org/diconde/iod/NdeDxCalibrationData") DS 1 KV Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const KVUsedInGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091071), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1072,"astm.org/diconde/iod/NdeDxCalibrationData") DS 1 MAs Used In Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const MAsUsedInGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091072), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1073,"astm.org/diconde/iod/NdeDxCalibrationData") DS 1 Number of Frames RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const NumberOfFrames_DxCalData : Tag = Tag{ key: TagKey(0x00091073), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1074,"astm.org/diconde/iod/NdeDxCalibrationData") LO 1 Filter Material Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const FilterMaterialUsedInGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091074), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1075,"astm.org/diconde/iod/NdeDxCalibrationData") DS 1 Filter Thickness Used in Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const FilterThicknessUsedInGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091075), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1076,"astm.org/diconde/iod/NdeDxCalibrationData") DA 1-n Date of Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const DateOfGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091076), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1077,"astm.org/diconde/iod/NdeDxCalibrationData") TM 1-n Time of Gain Calibration RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const TimeOfGainCalibration_DxCalData : Tag = Tag{ key: TagKey(0x00091077), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1080,"astm.org/diconde/iod/NdeDxCalibrationData") OB 1 Bad Pixel Image RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const BadPixelImage_DxCalData : Tag = Tag{ key: TagKey(0x00091080), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
/// (0009,1099,"astm.org/diconde/iod/NdeDxCalibrationData") LT 1 Calibration Notes RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const CalibrationNotes_DxCalData : Tag = Tag{ key: TagKey(0x00091099), creator: Some(Cow::Borrowed("astm.org/diconde/iod/NdeDxCalibrationData"))};
