// This file contains constant definition for [Meta] information
// for the DICOM constant tags.
//
// Do not edit! This file was autogenerated with `mk-tags-rs`
// utility on Sun, 22 Jan 2023 21:30:50 +0300 by "stingx" on "desktop-2iqn19a".
//
// Full command line:
// target\debug\mk-tags-rs.exe -i libs/dpx-dicom-core/etc/generic.tsv -a utils/mk-tags-rs/generic_tags_header.txt -t libs/dpx-dicom-core/src/tags/generic.rs -m libs/dpx-dicom-core/src/tag/generic_meta.rs
//

#![allow(missing_docs)]

use crate::tag::StaticMetaList;
// cspell:disable

mod _internals {
    #![allow(unused_imports)]
    use crate::{ Tag, TagKey, tag::Source, tag::Meta, tag::PrivateIdentificationAction as Pia, Vr };
    use std::borrow::Cow;
    pub (super) static ALL_TAGS_META: [Meta; 4] = [
        Meta {tag: Tag{ key: TagKey(0x00000000), creator: None}, mask: 0x00000000, vr: (Vr::UN,Vr::Undefined,Vr::Undefined), vm: (0,0,1), name: Cow::Borrowed("Unknown"), keyword: Cow::Borrowed("Unknown"), source: Source::Invalid },
        Meta {tag: Tag{ key: TagKey(0x00000000), creator: None}, mask: 0x0001FFFF, vr: (Vr::UL,Vr::Undefined,Vr::Undefined), vm: (1,1,1), name: Cow::Borrowed("Group Length"), keyword: Cow::Borrowed("GroupLength"), source: Source::Retired },
        Meta {tag: Tag{ key: TagKey(0x00010000), creator: None}, mask: 0x0001FFFF, vr: (Vr::UL,Vr::Undefined,Vr::Undefined), vm: (1,1,1), name: Cow::Borrowed("Private Group Length"), keyword: Cow::Borrowed("PrivateGroupLength"), source: Source::Retired },
        Meta {tag: Tag{ key: TagKey(0x00010000), creator: None}, mask: 0x0001FF00, vr: (Vr::LO,Vr::Undefined,Vr::Undefined), vm: (1,1,1), name: Cow::Borrowed("Private Reservation"), keyword: Cow::Borrowed("PrivateReservation"), source: Source::Dicom },
    ];
}

pub static ALL_TAGS_META: StaticMetaList = StaticMetaList::new(&_internals::ALL_TAGS_META);