// This file contains constant definition for DICOM tags
//
// Do not edit! This file was autogenerated with `mk-tags-rs`
// utility on ${DATE} by "${USER}" on "${HOST}".
//
// Full command line:
// ${CMD_LINE}
//
