// This file contains constant definition for DICOM tags
//
// Do not edit! This file was autogenerated with `mk_tags_rs`
// utility on ${DATE} by "${USER}" on "${HOST}".
//
// Full command line:
// ${CMD_LINE}
//

use crate::Tag;
