// This file contains constant definition for DICOM tags
//
// Do not edit! This file was autogenerated with `mk-tags-rs`
// utility on Sun, 22 Jan 2023 21:30:50 +0300 by "stingx" on "desktop-2iqn19a".
//
// Full command line:
// target\debug\mk-tags-rs.exe -i libs/dpx-dicom-core/etc/generic.tsv -a utils/mk-tags-rs/generic_tags_header.txt -t libs/dpx-dicom-core/src/tags/generic.rs -m libs/dpx-dicom-core/src/tag/generic_meta.rs
//

//! Dictionary of generic catch-all Tag keys not listed in main DICOM standard
//!
//! Note: constant names in this module does not follow Rust naming
//! convention `UPPER_CASE_GLOBALS`, instead they are following
//! DICOM standard "keyword" names. This eases interoperability with
//! different libraries as well as with DICOM standard itself.

#![allow(non_upper_case_globals, unused_imports)]

use crate::{Tag, TagKey};
use std::borrow::Cow;
// cspell:disable

/// (XXXO,0000) UL 1 Group Length RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const GroupLength : Tag = Tag{ key: TagKey(0x00000000), creator: None};
/// (XXXN,0000) UL 1 Private Group Length RETIRED!
#[deprecated(note = "Retired DICOM tag")]
pub const PrivateGroupLength : Tag = Tag{ key: TagKey(0x00010000), creator: None};
/// (XXXN,00XX) LO 1 Private Reservation
pub const PrivateReservation : Tag = Tag{ key: TagKey(0x00010000), creator: None};
